// <auto-generated />
using System;
using LibraryApp.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryApp.DAL.Migrations
{
    [DbContext(typeof(LibreryContext))]
    [Migration("20180625195842_Add table LibraryWorks")]
    partial class AddtableLibraryWorks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryApp.DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("LibraryWorkId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("LibraryWorkId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryApp.DAL.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("LibraryWorkId");

                    b.HasKey("Id");

                    b.HasIndex("LibraryWorkId");

                    b.ToTable("Сlients");
                });

            modelBuilder.Entity("LibraryApp.DAL.Models.LibraryWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActualDateReturn");

                    b.Property<DateTime>("PromiseDateReturn");

                    b.HasKey("Id");

                    b.ToTable("LibraryWorks");
                });

            modelBuilder.Entity("LibraryApp.DAL.Models.Book", b =>
                {
                    b.HasOne("LibraryApp.DAL.Models.LibraryWork")
                        .WithMany("Books")
                        .HasForeignKey("LibraryWorkId");
                });

            modelBuilder.Entity("LibraryApp.DAL.Models.Client", b =>
                {
                    b.HasOne("LibraryApp.DAL.Models.LibraryWork")
                        .WithMany("Clients")
                        .HasForeignKey("LibraryWorkId");
                });
#pragma warning restore 612, 618
        }
    }
}
